---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: golang
  commands:
  - echo step 1

- name: condition
  image: golang
  commands:
  - echo step 2
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - "refs/tags/*"

when:
  event:
    exclude:
    - promote

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test_deploy
  image: golang
  commands:
  - echo deploying....
  - echo yay


when:
  event:
  - promote
  target:
  - promote-stable

