---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: golang
  commands:
  - exit 1

- name: condition
  image: golang
  commands:
  - echo step 2
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - "refs/tags/*"


- name: slack_notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    username: bill_maxwell
  when:
    status: [ failure ]
    event:
      exclude:
      - pull_request

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
name: promotions

platform:
  os: linux
  arch: arm64

steps:
- name: test_deploy
  image: golang
  commands:
  - echo deploying....${DRONE_TAG}
  - echo yay


trigger:
  event:
  - promote
  target:
  - promote-stable

